### ISSUE TITLE
creators cant upload

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/studio#5]
Due to some strange error, the Creators can't currently upload models. We should investigate and fix this.

**Comment by l-silvestre** [comment]
Arweave.app silently disconnects when user manually closes popup after initial connect

**Comment by PTiagorio** [comment]
Also fix: arconnect shows up disabled on first usage and needs reload to work

**Comment by l-silvestre** [comment]
As discussed, arweave.app support will be dropped in studio until a later date when bundlr or arweave.app fixes the issues
