### ISSUE TITLE
missing label when uploading

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/studio#87]
When uploading a model on the Studio app, a label should be added to explain what the markdown is for. This shouldn't be the case, and we received a complaint from users related to this.

**Comment by l-silvestre** [comment]
Also add withdraw funds form bundlr functionality

**Comment by l-silvestre** [comment]
Fix update Script flow console error breaking upload

**Comment by l-silvestre** [comment]
Fix buttons stays disabled after failed attempt, preventing retries without reloading ui and refilling steps
